/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router


import type { LazyRouteFunction, RouteObject } from "react-router-dom";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";
type CustomRouteObject = Omit<RouteObject, 'Component'|'index'> & {
  Component?: React.ComponentType<any>|null;
};

export const layouts: Record<RouteLayout, LazyRouteFunction<CustomRouteObject>> = {
  base: () => import("@/layouts/base-layout/index.tsx"),
  blank: () => import("@/layouts/blank-layout/index.tsx"),
};

export const pages: Record<LastLevelRouteKey, LazyRouteFunction<CustomRouteObject>> = {
  403: () => import("@/pages/_builtin/403/index.tsx"),
  404: () => import("@/pages/_builtin/404/index.tsx"),
  500: () => import("@/pages/_builtin/500/index.tsx"),
  "iframe-page": () => import("@/pages/_builtin/iframe-page/[url].tsx"),
  about: () => import("@/pages/about/index.tsx"),
  administrative_framework: () => import("@/pages/administrative/framework/index.tsx"),
  "administrative_message-detail": () => import("@/pages/administrative/message-detail/index.tsx"),
  administrative_message: () => import("@/pages/administrative/message/index.tsx"),
  administrative_organization: () => import("@/pages/administrative/organization/index.tsx"),
  "administrative_post-manage": () => import("@/pages/administrative/post-manage/index.tsx"),
  features_captcha: () => import("@/pages/features/captcha/index.tsx"),
  features_colorthief: () => import("@/pages/features/colorthief/index.tsx"),
  features_draggable: () => import("@/pages/features/draggable/index.tsx"),
  "features_eye-dropper": () => import("@/pages/features/eye-dropper/index.tsx"),
  features_flow: () => import("@/pages/features/flow/index.tsx"),
  features_gantt: () => import("@/pages/features/gantt/index.tsx"),
  features_lazyload: () => import("@/pages/features/lazyload/index.tsx"),
  features_pickr: () => import("@/pages/features/pickr/index.tsx"),
  features_print: () => import("@/pages/features/print/index.tsx"),
  features_swiper: () => import("@/pages/features/swiper/index.tsx"),
  features_viewer: () => import("@/pages/features/viewer/index.tsx"),
  "features_vue-directive": () => import("@/pages/features/vue-directive/index.tsx"),
  "features_vue-office": () => import("@/pages/features/vue-office/index.tsx"),
  features_waterfall: () => import("@/pages/features/waterfall/index.tsx"),
  home: () => import("@/pages/home/index.tsx"),
  login: () => import("@/pages/login/index.tsx"),
  "system-manage_internalization": () => import("@/pages/system-manage/internalization/index.tsx"),
  "system-manage_menu-manage": () => import("@/pages/system-manage/menu-manage/index.tsx"),
  "system-manage_operation-log": () => import("@/pages/system-manage/operation-log/index.tsx"),
  "system-manage_role-manage": () => import("@/pages/system-manage/role-manage/index.tsx"),
  "system-manage_user-manage": () => import("@/pages/system-manage/user-manage/index.tsx"),
  "user-center": () => import("@/pages/user-center/index.tsx"),
};
