/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 10
    }
  },
  {
    name: 'administrative',
    path: '/administrative',
    component: 'layout.base',
    meta: {
      i18nKey: 'route.administrative',
      title: 'administrative'
    },
    children: [
      {
        name: 'administrative_framework',
        path: 'framework',
        component: 'view.administrative_framework',
        meta: {
          i18nKey: 'route.administrative_framework',
          title: 'administrative_framework'
        }
      },
      {
        name: 'administrative_message',
        path: 'message',
        component: 'view.administrative_message',
        meta: {
          i18nKey: 'route.administrative_message',
          title: 'administrative_message'
        }
      },
      {
        name: 'administrative_message-detail',
        path: 'message-detail',
        component: 'view.administrative_message-detail',
        meta: {
          i18nKey: 'route.administrative_message-detail',
          title: 'administrative_message-detail'
        }
      },
      {
        name: 'administrative_organization',
        path: 'organization',
        component: 'view.administrative_organization',
        meta: {
          i18nKey: 'route.administrative_organization',
          title: 'administrative_organization'
        }
      },
      {
        name: 'administrative_post-manage',
        path: 'post-manage',
        component: 'view.administrative_post-manage',
        meta: {
          i18nKey: 'route.administrative_post-manage',
          title: 'administrative_post-manage'
        }
      }
    ]
  },
  {
    name: 'features',
    path: '/features',
    component: 'layout.base',
    meta: {
      i18nKey: 'route.features',
      title: 'features'
    },
    children: [
      {
        name: 'features_captcha',
        path: 'captcha',
        component: 'view.features_captcha',
        meta: {
          i18nKey: 'route.features_captcha',
          title: 'features_captcha'
        }
      },
      {
        name: 'features_colorthief',
        path: 'colorthief',
        component: 'view.features_colorthief',
        meta: {
          i18nKey: 'route.features_colorthief',
          title: 'features_colorthief'
        }
      },
      {
        name: 'features_draggable',
        path: 'draggable',
        component: 'view.features_draggable',
        meta: {
          i18nKey: 'route.features_draggable',
          title: 'features_draggable'
        }
      },
      {
        name: 'features_eye-dropper',
        path: 'eye-dropper',
        component: 'view.features_eye-dropper',
        meta: {
          i18nKey: 'route.features_eye-dropper',
          title: 'features_eye-dropper'
        }
      },
      {
        name: 'features_flow',
        path: 'flow',
        component: 'view.features_flow',
        meta: {
          i18nKey: 'route.features_flow',
          title: 'features_flow'
        }
      },
      {
        name: 'features_gantt',
        path: 'gantt',
        component: 'view.features_gantt',
        meta: {
          i18nKey: 'route.features_gantt',
          title: 'features_gantt'
        }
      },
      {
        name: 'features_lazyload',
        path: 'lazyload',
        component: 'view.features_lazyload',
        meta: {
          i18nKey: 'route.features_lazyload',
          title: 'features_lazyload'
        }
      },
      {
        name: 'features_pickr',
        path: 'pickr',
        component: 'view.features_pickr',
        meta: {
          i18nKey: 'route.features_pickr',
          title: 'features_pickr'
        }
      },
      {
        name: 'features_print',
        path: 'print',
        component: 'view.features_print',
        meta: {
          i18nKey: 'route.features_print',
          title: 'features_print'
        }
      },
      {
        name: 'features_swiper',
        path: 'swiper',
        component: 'view.features_swiper',
        meta: {
          i18nKey: 'route.features_swiper',
          title: 'features_swiper'
        }
      },
      {
        name: 'features_viewer',
        path: 'viewer',
        component: 'view.features_viewer',
        meta: {
          i18nKey: 'route.features_viewer',
          title: 'features_viewer'
        }
      },
      {
        name: 'features_vue-directive',
        path: 'vue-directive',
        component: 'view.features_vue-directive',
        meta: {
          i18nKey: 'route.features_vue-directive',
          title: 'features_vue-directive'
        }
      },
      {
        name: 'features_vue-office',
        path: 'vue-office',
        component: 'view.features_vue-office',
        meta: {
          i18nKey: 'route.features_vue-office',
          title: 'features_vue-office'
        }
      },
      {
        name: 'features_waterfall',
        path: 'waterfall',
        component: 'view.features_waterfall',
        meta: {
          i18nKey: 'route.features_waterfall',
          title: 'features_waterfall'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'login',
    path: '/login',
    component: 'layout.blank$view.login',
    layout: 'blank',
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system-manage',
    path: '/system-manage',
    component: 'layout.base',
    meta: {
      i18nKey: 'route.system-manage',
      title: 'system-manage'
    },
    children: [
      {
        name: 'system-manage_internalization',
        path: 'internalization',
        component: 'view.system-manage_internalization',
        meta: {
          i18nKey: 'route.system-manage_internalization',
          title: 'system-manage_internalization'
        }
      },
      {
        name: 'system-manage_menu-manage',
        path: 'menu-manage',
        component: 'view.system-manage_menu-manage',
        meta: {
          i18nKey: 'route.system-manage_menu-manage',
          title: 'system-manage_menu-manage'
        }
      },
      {
        name: 'system-manage_operation-log',
        path: 'operation-log',
        component: 'view.system-manage_operation-log',
        meta: {
          i18nKey: 'route.system-manage_operation-log',
          title: 'system-manage_operation-log'
        }
      },
      {
        name: 'system-manage_role-manage',
        path: 'role-manage',
        component: 'view.system-manage_role-manage',
        meta: {
          i18nKey: 'route.system-manage_role-manage',
          title: 'system-manage_role-manage'
        }
      },
      {
        name: 'system-manage_user-manage',
        path: 'user-manage',
        component: 'view.system-manage_user-manage',
        meta: {
          i18nKey: 'route.system-manage_user-manage',
          title: 'system-manage_user-manage'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
